# Install MySQL as Database.
- name: MySQL | Install MySQL packages
  apt:
    pkg: "{{ item }}"
    state: present
  with_items:
    - mysql-server
    - mysql-client

# Install MySQL as php extension.
- name: MySQL | Install MySQL - PHP library.
  apt:
    pkg: "{{ item }}"
    state: present
  with_items:
    - php5-mysql
  when: php

# Let's run our MySQL server.
- name: MySQL | Ensure MySQL Server is running
  service:
    name: mysql
    state: started
    enabled: yes

# Let's replace the MySQL config file.
- name: MySQL | Replace MySQL config file.
  template:
    src: "../templates/my.j2"
    dest: "/etc/mysql/my.cnf"

# Let's check if we're able to log into the sql using our password.
- name: MySQL | Check if we're ok to log in
  command: mysqladmin -uroot -p{{ db_password }} status
  register: login_attempt
  ignore_errors: True

## If not, than change it.
- name: MySQL | Change the password for the root user
  command: mysqladmin -uroot password {{ db_password }}
  when: login_attempt|failed
  register: change_password

# We need to be able to login to the mysql server
- name: MySQL | Allow root login
  shell: echo "create user 'root'@'%' identified by '{{ db_password }}';" | mysql -u root -p{{ db_password }};
  when: not change_password|skipped and change_password|success
  register: allow_user

# Grant privileges to the user.
- name: MySQL | Grand Privileges
  shell: echo "grant all privileges on *.* to 'root'@'%' with grant option;" | mysql -u root -p{{ db_password }};
  when: not allow_user|skipped
  register: grant_priv

# Flush privileges for the better.
- name: MySQL | Flush Privileges
  shell: echo "flush privileges;" | mysql -u root -p{{ db_password }};
  when: not grant_priv|skipped
  register: flush_priv

# Restart MySQL server if previous actions were performed.
- name: MySQL | Restart MySQL server
  service:
    name: mysql
    state: restarted

# Restart MySQL server if previous actions were performed.
- name: MySQL | Restart PHP
  service:
    name: php5-fpm
    state: restarted